#!/bin/sh

#
# Copyright (c) 2007 by Cisco Systems, Inc.
# All rights reserved.
#

TEMPLATE_FILE='vqec_version.h.tmpl'
VERSION_FILE='vqec_version.h'
TEMP_FILE='vqec_version.h.tmp'

build_user=$USER
build_path=$PWD
build_type='development'

build_refpoint=""
if [ -e .ACME/component.info ]; then
 build_refpoint=$(sed 's/vam\/eva:source:.*:.*://g' .ACME/component.info)
fi

print_help() {
   echo "Usage: update_version.sh [<build-type>]"
   echo "  where <build-type> is one of:"
   echo "    development: used for development build"
   echo "    production: used for production build"
   echo "    rc-<n>: used for building release candidate <n>"
   echo "  If <build-type> is not specified, 'development' will be used"
   exit 1
}

if [ $# -gt 1 ];then
   print_help
fi

if [ "$1" = "production" ] || [ `expr index "$1" "rc-"` -eq 1 ];then
   build_type=$1
elif [ $# -eq 0 ];then
   build_type='development'
else
   print_help
fi

# just use the build-number from the template file
if [ -e "$TEMPLATE_FILE" ];then
   awk '/VQEC_VAR_BUILD_NUMBER/ ' $TEMPLATE_FILE > ver.$$
   version=$(sed '/#define VQEC_VAR_BUILD_NUMBER /s///g' ver.$$)
fi
if [ -z $version ]; then
	version=0
fi

echo "/*" > $TEMP_FILE
echo " *  THIS FILE IS AUTOMATICALLY GENERATED." >> $TEMP_FILE
echo " *  DO NOT EDIT THIS FILE!!" >> $TEMP_FILE
echo " */" >> $TEMP_FILE
echo "" >> $TEMP_FILE

sed '/^.*VQEC_VAR.*$/d' $TEMPLATE_FILE >> $TEMP_FILE

#
# temporarily just fixing VQEC_VAR_BUILD_NUMBER to 1 so as
# to not create confusion regarding build numbers in separate workspaces
#
echo "#define VQEC_VAR_BUILD_NUMBER ${version}" >> $TEMP_FILE
if [ $build_type = "development" ];then
    echo "#define VQEC_VAR_BUILD_TYPE \"${build_type}\"" >> $TEMP_FILE
    echo "#define VQEC_VAR_WS_PATH \"${build_path}\"" >> $TEMP_FILE
    echo "#define VQEC_VAR_BUILT_BY \"${build_user}\"" >> $TEMP_FILE
    echo "#define BUILD_REFPOINT \"${build_refpoint}\"" >> $TEMP_FILE
fi

#create the new/updated version file if necessary
diff -q $TEMP_FILE $VERSION_FILE
if [ "$?" -ne 0 ];then
    echo writing new vqec_version.h...
    cp $TEMP_FILE $VERSION_FILE
fi

#clean up
rm -f $TEMP_FILE
rm -f ver.$$


