#
# Copyright (c) 2006-2008 by Cisco Systems, Inc.
# All Rights Reserved.
#
# always include vqe.mk and vqe_targets.mk first to define 
# global build targets
include ../../../vqe.mk
include ../../../vqe_targets.mk

BUILD_PRODUCTS = vqes

%::
	$(CHECK_MAKE_TARGET)
