/********************************************************************
 * vqe_utils_syslog_def.h
 *
 * This file defines the SYSLOG messages for VQE-UTILS
 *
 * Copyright (c) 2008 by Cisco Systems, Inc.
 * All rights reserved.
 *
 *********************************************************************/

#ifndef _VQE_UTILS_SYSLOG_DEF_H_
#define _VQE_UTILS_SYSLOG_DEF_H_

#include <log/syslog_macros.h>
#include <log/vqe_id.h>

syslog_facilitydef(VQENAME_VQE_UTILS, LOG_VQE_UTILS, LOG_INFO);

#define VQE_UTILS_OPER_FAILURE_ACTION                                    \
    "Perform any actions associated with the additional error messages " \
    "that occur together with this error message. If any of these indicates " \
    "that you should contact your Cisco technical support representative, " \
    "then copy this error message exactly as it appears in the system log " \
    "and provide it, in addition to any other requested information, when " \
    "you contact your technical support representative."    

/*  message priorities:
 *   LOG_CRIT
 *   LOG_ERR
 *   LOG_INFO
 */

syslog_msgdef(LOG_VQE_UTILS, VQE_HASH_MALLOC_FAILURE, LOG_ERR,
              "Memory allocation for hash table data structures failed, "
              "(detail %s)");
msgdef_explanation("The hash table API failed to allocate memory. "
                   "The text of the error message provides additional detail"
                   " on the failure.");
msgdef_recommended_action(SYSLOGDOC_REPORT_COPY_CONTACT
                          SYSLOGDOC_RESTART_VQES);

syslog_msgdef(LOG_VQE_UTILS, VQE_HASH_BAD_ARG, LOG_ERR, 
              "A bad parameter was passed to the hash table API (detail: %s).");
msgdef_explanation("A bad parameter was passed to the hash table API by a "
                   "client process. The text of the error message provides "
                   "additional detail on the bad parameter value.");
msgdef_recommended_action(VQE_UTILS_OPER_FAILURE_ACTION);

syslog_msgdef(LOG_VQE_UTILS, VQE_HASH_INSERT_FAILURE, LOG_ERR, 
              "Insertion of an element into the hash table failed (detail %s)");
msgdef_explanation("Insertion of an element into the hash table by a client "
                    "process failed. The text of the error message provides "
                    "additional detail on the cause of the failure");
msgdef_recommended_action(VQE_UTILS_OPER_FAILURE_ACTION);

syslog_msgdef(LOG_VQE_UTILS, VQE_HASH_REMOVE_FAILURE, LOG_ERR, 
              "Removal of a requested element from the hash table failed "
              "(detail %s)");
msgdef_explanation("The requested removal of an element from the hash table by"
                   " a client process failed. The text of the error message "
                   "provides additional detail on the cause of the failure");
msgdef_recommended_action(VQE_UTILS_OPER_FAILURE_ACTION);

syslog_msgdef(LOG_VQE_UTILS, VQE_MP_TLV_ERR_PKTDEC, LOG_ERR,
              "Problem in decoding (detail: %s)");
msgdef_explanation("Error decoding TLV packets. "
                   "The text of the error message provides additional detail"
                   " on the failure.");
msgdef_recommended_action(VQE_UTILS_OPER_FAILURE_ACTION);


syslog_msgdef(LOG_VQE_UTILS, VQE_MP_TLV_ERR_BUF_TOO_SMALL, LOG_ERR,
             "Problem with MP_TLV Buffer size (detail: %s)");
msgdef_explanation("The buffer into which a write was attempted was too small"
                   "The text of the error message provides additional detail"
                   " on the failure.");
msgdef_recommended_action(VQE_UTILS_OPER_FAILURE_ACTION);


syslog_msgdef(LOG_VQE_UTILS, VQE_MP_TLV_ERR_OUTBUF_PAD, LOG_ERR,
              "Error related to output buffer padding (detail: %s)");
msgdef_explanation("Padding output buffer failed."
                   "The text of the error message provides additional detail"
                   " on the failure.");
msgdef_recommended_action(VQE_UTILS_OPER_FAILURE_ACTION);

syslog_msgdef(LOG_VQE_UTILS, VQE_MP_TLV_ERR_PKT_DEC_TYPE, LOG_ERR,
              "Error in TLV packet type (detail: %s)");
msgdef_explanation("Error decoding TLV packet type"
                   "The text of the error message provides additional detail"
                   " on the failure.");
msgdef_recommended_action(VQE_UTILS_OPER_FAILURE_ACTION);


syslog_msgdef(LOG_VQE_UTILS, VQE_MP_TLV_ERR_PID, LOG_ERR,
              "Error in PID (detail: %s)");
msgdef_explanation("The PID for the packet was not found"
                   "The text of the error message provides additional detail"
                   " on the failure.");
msgdef_recommended_action(VQE_UTILS_OPER_FAILURE_ACTION);

syslog_msgdef(LOG_VQE_UTILS, VQE_MP_TLV_INFO, LOG_INFO,
              "MP_TLV related info message (detail: %s)");
msgdef_explanation("This is an informational message generated by MP_TLV."
                   "The text of the error message provides additional detail"
                   " on the failure.");
msgdef_recommended_action(SYSLOGDOC_INFO_ONLY);

#endif /* _VQE_UTILS_SYSLOG_DEF_H_ */
