#
# Copyright (c) 2006-2007 by Cisco Systems, Inc.
# All Rights Reserved.
#

#always include vqe.mk, vqe_builds.mk and  vqec.mk first
include ../../vqe.mk
include ../../environ.mk
include ../../vqe_builds.mk
include ../vqec.mk

# Include the BUILD file for the component we want to build.
# This will first build dependencies and then the build target.
include $(SRCDIR)/BUILD
